/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AsyncCmp {
    }
    interface BlogPost {
        "data": any;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAsyncCmpElement extends Components.AsyncCmp, HTMLStencilElement {
    }
    var HTMLAsyncCmpElement: {
        prototype: HTMLAsyncCmpElement;
        new (): HTMLAsyncCmpElement;
    };
    interface HTMLBlogPostElement extends Components.BlogPost, HTMLStencilElement {
    }
    var HTMLBlogPostElement: {
        prototype: HTMLBlogPostElement;
        new (): HTMLBlogPostElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "async-cmp": HTMLAsyncCmpElement;
        "blog-post": HTMLBlogPostElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AsyncCmp {
    }
    interface BlogPost {
        "data"?: any;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "async-cmp": AsyncCmp;
        "blog-post": BlogPost;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "async-cmp": LocalJSX.AsyncCmp & JSXBase.HTMLAttributes<HTMLAsyncCmpElement>;
            "blog-post": LocalJSX.BlogPost & JSXBase.HTMLAttributes<HTMLBlogPostElement>;
        }
    }
}
